### tigger
POST http://localhost:9000/api/v1/tigger/s3events
Content-Type: application/json

{
    "events":[
        {
            "s3bucket": "tamidb-1251014631",
            "s3key": "367fb8f59f92e9b1cb0820f692e4c0d426a886043dd6ae1eac2fbc6cacf6cada-1713617282229704000.redolog"
        }
    ]
}