### create tables
POST http://localhost:18090/api/v1/createdb
Content-Type: application/json

{
    "list": [
        {
            "cmd": "CREATE TABLE IF NOT EXISTS foo1 (id text NOT NULL PRIMARY KEY,title text)",
            "args": []
        },
        {
            "cmd": "CREATE TABLE IF NOT EXISTS foo2 (id text NOT NULL PRIMARY KEY,title text)",
            "args": []
        },
        {
            "cmd": "INSERT INTO foo1 (id, title) values (?, ?)",
            "args": [415, "romantic-swell"]
        },
        {
            "cmd": "INSERT INTO foo2 (id, title) values (?, ?)",
            "args": [415, "romantic-swell"]
        }
    ]
}

### 
{
  "read_key": "25c6wiS4yjBs",
  "write_key": "uZiuaZXjr4hgxo5JzxfxJEQatpCMc2of"
}
{
  "read_key": "FvcbcWMvKkIZ",
  "write_key": "3tITktTH5J0BbztgSblRiea6lruUGiT1"
}
{
  "read_key": "HjJBQPI3IR2e",
  "write_key": "v0izSDPyHWKa09Drzv5itYKUha1WqEUy"
}
{
  "read_key": "WsIJ4LK7kRbY",
  "write_key": "prLuUDhh5Xi9SHv1z5XMuD5sWVt9jJTv"
}
{
  "code": 0,
  "message": "OK",
  "data": {
    "read_key": "TpCv3b98ZnzV",
    "write_key": "YzhNz3BwTVWSxO2tXRb4IBserhUHc5ic"
  }
}
{
  "code": 0,
  "message": "OK",
  "data": {
    "read_key": "123eeeb5e0aeb791e8332f8bace4b39408efbb",
    "write_key": "123eeeb5e0aeb7bdf46b05b5afaac1c035caa6686da5843e9a218311adb1fdc2d83aa8b385ce4a"
  }
}

{
  "code": 0,
  "message": "OK",
  "data": {
    "readkey": "123eeeb5e0aeb787d23c00ea8ae1c6f43fe7bf",
    "writekey": "123eeeb5e0aeb7a7df0c29a994bccfd144f19b7146a1a03c8235a527da8ac9e7b751d9ae8fd909"
  }
}

{
  "code": 0,
  "message": "OK",
  "data": {
    "readkey": "123eeeb5e0aeb7878d3b7cadb9baf7d03ce6ef",
    "writekey": "123eeeb5e0aeb7b0ed36378da8a6ecf315fc980f68b2b3208829a32ed589f5dfba1aebeeb7eb51"
  }
}