### tigger
POST http://localhost:9000/api/v1/tigger/s3events
Content-Type: application/json

{
    "events":[
        {
            "s3bucket": "tamidb-1251014631",
            "s3key": "367fb8f59f92e9b1cb0820f68abbf3d51cd6be535a8d9110cf08a431f5b2f4f0-1713092056336277000.redolog"
        }
    ]
}