### account login
POST http://localhost:3001/api/AccountLogin
Content-Type: application/json
X-Http-Method-Override: override

{"username":"zhoulv","password":"zhoulv12345"}

### account profile
GET http://localhost:3001/api/AccountProfile
Content-Type: application/json