### application my
POST http://localhost:3001/api?fn=ApplicationMy
Content-Type: application/json

### application specs
POST http://localhost:3001/api?fn=ApplicationSpecs
Content-Type: application/json