### apps my
POST http://localhost:3001/api/AppsMy
Content-Type: application/json

### apps specs
http://localhost:3001/api/AppsSpecs
Content-Type: application/json

### apps info
http://localhost:3001/api/AppsInfo
Content-Type: application/json