name: Go1.21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install sqlite3
      run: sudo apt-get install sqlite3 libsqlite3-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'

    - name: Build
      run: go mod tidy && cd cmd/http && go build .

    - name: Test
      run: go test ./...